import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useRef, MouseEvent } from "react";
import { Brand } from "../components";

const Home: NextPage = () => {

  const emailRef = useRef<HTMLInputElement>(null)

  const handleClick = (e: MouseEvent<HTMLButtonElement>) => {
    console.log(emailRef.current?.value);
  }


  return (
    <div>
      <Head>
        <title>Modern App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="section-padding gradient-bg flex lg:flex-col sm:py-16 sm:px-8 md:p-16">
        <div className="flex-1 flex justify-center items-start flex-col mr-20 lg:mb-12 lg:ml-12">
          <h1 className="gradient-text font-base font-extrabold text-5xl tracking-wider sm:text-4xl">
            Let&apos;s Build Something amazing with GPT-3 OpenAI
          </h1>
          <p className="font-base font-normal text-xl text-text mt-6 sm:text-sm">
            Yet bed any for travelling assistance indulgence unpleasing. Not
            thoughts all exercise blessing. Indulgence way everything joy
            alteration boisterous the attachment. Party we years to order allow
            asked of.
          </p>

          <div className="w-full mt-8 mx-0 mb-4 flex">
            <input ref={emailRef}  placeholder="Your Email Address" className="flex-[2] w-full min-h-[50px] font-base text-xl bg-footer border-2 border-solid border-footer py-0 px-4 text-white rounded-r sm:text-base" />
            <button onClick={handleClick} type="submit" className="flex-[0.6] w-full min-h-[50px] font-base font-bold text-xl bg-orange-600 rounded-r text-white py-0 px-4 sm:text-sm md:text-base" >Get Started</button>
          </div>

          <div className="w-full flex justify-start items-center mt-8 sm:flex-col">
            <Image src="/people.png" alt="people" width={180} height={40}/>
            <p className="ml-4 my-0 mt-0 font-base font-medium text-xs text-center text-white sm:m-0">1,600 people requested access a visit in last 24 hours</p>
          </div>
        </div>
        <div className="flex-1 flex justify-center items-center">
            <Image src="/ai.png" alt="ai" width={600} height={600}/>
          </div>
      </div>

      <Brand/>
    </div>
  );
};

export default Home;
